<?php
require_once 'config.php';
?>
<div class="mrc-calendar-widget">
  <div class="mrc-calendar-header">
    <h3>Calendar</h3>
  </div>
  <div class="mrc-calendar-nav">
    <button class="mrc-calendar-prev"><i class="fas fa-chevron-left"></i></button>
    <div class="mrc-calendar-title">JULY 2025</div>
    <button class="mrc-calendar-next"><i class="fas fa-chevron-right"></i></button>
  </div>
  <div class="mrc-calendar-grid">
    <div class="mrc-calendar-day-header">SUN</div>
    <div class="mrc-calendar-day-header">MON</div>
    <div class="mrc-calendar-day-header">TUE</div>
    <div class="mrc-calendar-day-header">WED</div>
    <div class="mrc-calendar-day-header">THU</div>
    <div class="mrc-calendar-day-header">FRI</div>
    <div class="mrc-calendar-day-header">SAT</div>
    <!-- Days will be generated by JS -->
  </div>
</div> 